zg/config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

post '/zg_git_hook', to: 'git_hook#index'
post '/zg_git_oauth', to: 'git_hook#oauth'

zg/app/models/ventura_comment.rb
class VenturaComment < ActiveRecord::Base
  unloadable
  belongs_to :journal, foreign_key: :journal_id, dependent: :destroy
end

zg/app/models/ventura_issue.rb
class VenturaIssue < ActiveRecord::Base
  unloadable
  belongs_to :issue, foreign_key: :issue_id
end

zg/app/models/ventura_project.rb
class VenturaProject < ActiveRecord::Base
  unloadable
  belongs_to :project, foreign_key: :project_id
end

zg/app/models/ventura_user.rb
class VenturaUser < ActiveRecord::Base
  unloadable
  belongs_to :user, foreign_key: :user_id
end

zg/app/controllers/git_hook_controller.rb
class GitHookController < ApplicationController
  skip_before_action :verify_authenticity_token

  def oauth
    begin
      Zg::GithubAdapter.create_access_token(oauth_params[:username],
                                            oauth_params[:password])
      flash[:notice] = 'Authorized successfully'
    rescue => e
      flash[:error] = e.message
    end

    redirect_to my_account_path(User.current)
  end

  def index
    github_hook = Zg::GithubHook.new(request.env['HTTP_X_GITHUB_EVENT'],
                                     git_payload)
    github_hook.process
    render json: 'success', status: 200
  end

  private

  def oauth_params
    params.require(:zg).permit(:username, :password)
  end

  def git_payload
    JSON.parse(params[:payload] || {})
  end
end

zg/app/views/my/_github_status.html.erb
<p>
  <%= label_tag :github_authorzied  %>
  <%= check_box_tag :github_authorzied,
                    nil,
                    User.current.authorized_github?,
                    disabled: true %>
</p>

zg/app/views/my/_oauth.html.erb
<% unless User.current.authorized_github? %>
  <%= form_tag zg_git_oauth_path do %>
    <fieldset class="box tabular">
      <legend>Github OAuth</legend>
      <p>
        <%= label_tag 'zg_username' do %>
          Username
          <span class="required">*</span>
        <% end %>
        <%= text_field_tag 'zg[username]' %>
      </p>
      <p>
        <%= label_tag 'zg_password' do %>
          Password
          <span class="required">*</span>
        <% end %>
        <%= password_field_tag 'zg[password]' %>
      </p>

      <%= submit_tag 'Authenticate' %>
    </fieldset>
  <% end %>
<% end %>

zg/app/views/my/account.html.erb
<div class="contextual">
  <%= additional_emails_link(@user) %>
  <%= link_to(l(:button_change_password), {:action => 'password'}, :class => 'icon icon-passwd') if @user.change_password_allowed? %>
  <%= call_hook(:view_my_account_contextual, :user => @user)%>
</div>

<h2>
  <%= avatar_edit_link(@user, :size => "50") %>
  <%=l(:label_my_account)%>
</h2>

<%= error_messages_for 'user' %>

<%= render 'oauth' %>

<%= labelled_form_for :user, @user,
                      :url => { :action => "account" },
                      :html => { :id => 'my_account_form',
                                 :method => :post, :multipart => true } do |f| %>
  <div class="splitcontentleft">
    <fieldset class="box tabular">
      <legend><%=l(:label_information_plural)%></legend>
      <p><%= f.text_field :firstname, :required => true %></p>
      <p><%= f.text_field :lastname, :required => true %></p>
      <p><%= f.text_field :mail, :required => true %></p>
      <% unless @user.force_default_language? %>
        <p><%= f.select :language, lang_options_for_select %></p>
      <% end %>
      <% if Setting.openid? %>
        <p><%= f.text_field :identity_url  %></p>
      <% end %>

      <% @user.custom_field_values.select(&:editable?).each do |value| %>
        <p><%= custom_field_tag_with_label :user, value %></p>
      <% end %>
      <%= call_hook(:view_my_account, :user => @user, :form => f) %>
    </fieldset>

    <p class="mobile-hide"><%= submit_tag l(:button_save) %></p>
  </div>

  <div class="splitcontentright">
    <fieldset class="box">
      <legend><%=l(:field_mail_notification)%></legend>
      <%= render :partial => 'users/mail_notifications' %>
    </fieldset>

    <fieldset class="box tabular">
      <legend><%=l(:label_preferences)%></legend>
      <%= render :partial => 'users/preferences' %>
      <%= call_hook(:view_my_account_preferences, :user => @user, :form => f) %>
    </fieldset>

    <p class="mobile-show"><%= submit_tag l(:button_save) %></p>
  </div>
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => 'sidebar' %>
<% end %>

<% html_title(l(:label_my_account)) -%>

zg/app/views/projects/_git_repo.html.erb
<p>
  <%= label_tag 'project[git_repo_url]' do %>
    Respository URL
  <% end %>
  <%= text_field_tag 'project[git_repo_url]',
                     project.ventura_project.try(:git_repo_url),
                     size: 60 %>
</p>

zg/app/views/projects/_zg_notify.html.erb
<% if User.current.logged? && project.sync_with_github? %>
  <div class="box">
    <h3 class="icon icon-issue">Github</h3>
    <p><%= image_tag 'true.png' %> <%= project.name %> is connected to Github</p>
    Please remember:
    <ul>
      <li>Authorize every member with Github</li>
      <li>Contact admin for any error</li>
    </ul>
  </div>
<% end %>

zg/app/views/users/_oauth.html.erb
<% if User.current.authorized_github? %>
  <div class="flash notice success">You authorized with Github</div>
<% else %>
  <%= form_tag zg_git_oauth_path do %>
    <fieldset class="box tabular">
      <legend>Github OAuth</legend>
      <p>
        <%= label_tag 'zg_username' do %>
          Username
          <span class="required">*</span>
        <% end %>
        <%= text_field_tag 'zg[username]' %>
      </p>
      <p>
        <%= label_tag 'zg_password' do %>
          Password
          <span class="required">*</span>
        <% end %>
        <%= password_field_tag 'zg[password]' %>
      </p>

      <%= submit_tag 'Authenticate' %>
    </fieldset>
  <% end %>
<% end %>